# Generated by Django 3.1.7 on 2021-04-04 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuarioId', models.AutoField(db_column='usuario_id', primary_key=True, serialize=False, unique=True)),
                ('usuarioNombre', models.CharField(db_column='usuario_nombre', max_length=45, verbose_name='Nombre del usuario')),
                ('usuarioApellido', models.CharField(db_column='usuario_apellido', max_length=45, verbose_name='Apellido del usuario')),
                ('usuarioEmail', models.EmailField(db_column='usuario_email', max_length=30, unique=True, verbose_name='Correo del usuario')),
                ('usuarioTipo', models.IntegerField(choices=[(1, 'ADMINISTRADOR'), (2, 'CLIENTE')], db_column='usuario_tipo', verbose_name='Tipo de usuario')),
                ('password', models.TextField(db_column='usuario_password', verbose_name='Controaseña del Usuario')),
                ('usuarioCelular', models.CharField(db_column='usuario_telefono', max_length=20, null=True, verbose_name='Telefono del usuario')),
                ('usuarioFoto', models.ImageField(db_column='usuario_foto', default='https://img2.freepng.es/20180331/eow/kisspng-computer-icons-user-clip-art-user-5abf13db298934.2968784715224718991702.jpg', null=True, upload_to='usuario/', verbose_name='Foto del usuario')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 't_usuarios',
            },
        ),
        migrations.CreateModel(
            name='VeterianriaModel',
            fields=[
                ('veterinariaId', models.AutoField(db_column='veterinaria_id', primary_key=True, serialize=False, unique=True)),
                ('veterinariaNombre', models.CharField(db_column='veterinaria_nombre', max_length=45, verbose_name='Nombre de la veterinaria')),
                ('veterinariaLogo', models.ImageField(db_column='veterinaria_logo', upload_to='veterinaria/', verbose_name='Logo de la veterinaria')),
                ('veterinariaDescripcion', models.TextField(db_column='veterinaria_descripcion', verbose_name='Descripcion de la veterinaria')),
                ('veterinariaTelefono', models.CharField(db_column='veterinaria_telefono', max_length=15, verbose_name='Telefono de la Empresa')),
                ('veterinariaDireccion', models.TextField(db_column='veterinaria_direccion', verbose_name='Direccion de la veterinaria')),
            ],
            options={
                'verbose_name': 'Veterinaria',
                'db_table': 't_veterinaria',
            },
        ),
        migrations.CreateModel(
            name='VeterinarioModel',
            fields=[
                ('veterinarioId', models.AutoField(db_column='veterinario_id', primary_key=True, serialize=False, unique=True)),
                ('veterinarioNombre', models.CharField(db_column='veterinario_nombre', max_length=45, verbose_name='Nombre de la veterinaria')),
                ('veterinarioApellido', models.CharField(db_column='veterinario_apellido', max_length=45, verbose_name='Apellido de la veterinaria')),
                ('veterinarioFoto', models.ImageField(db_column='veterinaria_foto', upload_to='veterinario/', verbose_name='Foto del veterinario')),
                ('veterinaria', models.ForeignKey(db_column='veterinaria_id', on_delete=django.db.models.deletion.CASCADE, related_name='veterinaria', to='citas_veterinaria.veterianriamodel')),
            ],
            options={
                'verbose_name': 'veterinario',
                'db_table': 't_veterinario',
            },
        ),
        migrations.CreateModel(
            name='ServicioModel',
            fields=[
                ('servicioId', models.AutoField(db_column='servicio_id', primary_key=True, serialize=False, unique=True)),
                ('servicioNombre', models.CharField(db_column='servicio_nombre', max_length=45, verbose_name='Nombre del servicio')),
                ('veterinaria', models.ForeignKey(db_column='veterinaria_id', on_delete=django.db.models.deletion.CASCADE, related_name='veterinariaServicio', to='citas_veterinaria.veterianriamodel')),
            ],
            options={
                'verbose_name': 'servicio',
                'db_table': 't_servicio',
            },
        ),
        migrations.CreateModel(
            name='SedeModel',
            fields=[
                ('sedeId', models.AutoField(db_column='sede_id', primary_key=True, serialize=False, unique=True)),
                ('sedeDireccion', models.TextField(db_column='sede_direccion', verbose_name='Direccion de la empresa')),
                ('veterinaria', models.ForeignKey(db_column='veterinaria_id', on_delete=django.db.models.deletion.CASCADE, related_name='veterinariaSede', to='citas_veterinaria.veterianriamodel')),
            ],
            options={
                'verbose_name': 'sede',
                'db_table': 't_sede',
            },
        ),
        migrations.CreateModel(
            name='CitaModel',
            fields=[
                ('citaId', models.AutoField(db_column='cita_id', primary_key=True, serialize=False, unique=True)),
                ('citaFecha', models.DateField(db_column='cita_fecha', verbose_name='Fecha de la cita')),
                ('citaCosto', models.DecimalField(db_column='cita_costo', decimal_places=3, max_digits=6, verbose_name='Costo de la cita')),
                ('cliente', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(db_column='sede_id', on_delete=django.db.models.deletion.CASCADE, related_name='sede', to='citas_veterinaria.sedemodel')),
                ('servicio', models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicio', to='citas_veterinaria.serviciomodel')),
                ('veterinaria', models.ForeignKey(db_column='veterinaria_id', on_delete=django.db.models.deletion.CASCADE, related_name='veterinariaCita', to='citas_veterinaria.veterianriamodel')),
            ],
            options={
                'verbose_name': 'cita',
                'db_table': 't_cita',
            },
        ),
    ]
