# Generated by Django 3.1.7 on 2021-04-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomodel',
            name='password',
            field=models.TextField(db_column='usuario_password', verbose_name='Contraseña del Usuario'),
        ),
    ]
