# Generated by Django 3.1.7 on 2021-04-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_veterinaria', '0002_auto_20210404_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinariomodel',
            name='veterinarioDescripcion',
            field=models.TextField(db_column='veterinario_descripcion', default=None, verbose_name='Descripcion del veterinario'),
            preserve_default=False,
        ),
    ]
