# Generated by Django 3.1.7 on 2021-04-06 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas_veterinaria', '0003_veterinariomodel_veterinariodescripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciomodel',
            name='veterinaria',
            field=models.ForeignKey(db_column='veterinaria_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicioVeterinaria', to='citas_veterinaria.veterianriamodel', null=False),
        ),
        migrations.AlterField(
            model_name='veterinariomodel',
            name='veterinaria',
            field=models.ForeignKey(db_column='veterinaria_id', on_delete=django.db.models.deletion.CASCADE, related_name='veterinariosVeterinaria', to='citas_veterinaria.veterianriamodel', null=False),
        ),
    ]
