# Generated by Django 3.1.7 on 2021-04-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_veterinaria', '0005_auto_20210406_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuarioCelular',
            field=models.CharField(db_column='usuario_telefono', default=None, max_length=20, verbose_name='Telefono del usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuarioFoto',
            field=models.ImageField(db_column='usuario_foto', default=None, upload_to='usuario/', verbose_name='Foto del usuario'),
            preserve_default=False,
        ),
    ]
