# Generated by Django 3.1.7 on 2021-04-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_veterinaria', '0006_auto_20210406_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotaModel',
            fields=[
                ('mascotaId', models.AutoField(db_column='mascota_id', primary_key=True, serialize=False, unique=True)),
                ('mascotaNombre', models.CharField(db_column='mascota_nombre', max_length=55, unique=True, verbose_name='Nombre de la Mascota')),
                ('mascotaEdad', models.IntegerField(db_column='mascota_edad', verbose_name='Edad de la Mascota')),
            ],
            options={
                'verbose_name': 'mascota',
                'db_table': 't_mascota',
            },
        ),
    ]
