# Generated by Django 3.1.7 on 2021-04-07 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas_veterinaria', '0007_mascotamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciomodel',
            name='veterinaria',
            field=models.ForeignKey(db_column='veterinaria_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicioVeterinaria', to='citas_veterinaria.veterianriamodel'),
        ),
    ]
