# Generated by Django 3.1.7 on 2021-04-09 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas_veterinaria', '0008_auto_20210406_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotamodel',
            name='cliente',
            field=models.ForeignKey(db_column='usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mascotaUsuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de la Mascota'),
        ),
        migrations.AddField(
            model_name='serviciomodel',
            name='servicioDescripcion',
            field=models.TextField(db_column='servicio_descripcion', default=None, verbose_name='Descripcion del servicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviciomodel',
            name='servicioFoto',
            field=models.ImageField(db_column='servicio_foto', null=True, upload_to='servicio/', verbose_name='Foto del Servicio'),
        ),
        migrations.AlterField(
            model_name='citamodel',
            name='cliente',
            field=models.ForeignKey(db_column='usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='citamodel',
            name='sede',
            field=models.ForeignKey(db_column='sede_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sede', to='citas_veterinaria.sedemodel'),
        ),
        migrations.AlterField(
            model_name='citamodel',
            name='servicio',
            field=models.ForeignKey(db_column='servicio_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio', to='citas_veterinaria.serviciomodel'),
        ),
        migrations.AlterField(
            model_name='sedemodel',
            name='veterinaria',
            field=models.ForeignKey(db_column='veterinaria_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veterinariaSede', to='citas_veterinaria.veterianriamodel'),
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuarioCelular',
            field=models.CharField(db_column='usuario_telefono', max_length=20, null=True, verbose_name='Telefono del usuario'),
        ),
        migrations.AlterField(
            model_name='veterinariomodel',
            name='veterinaria',
            field=models.ForeignKey(db_column='veterinaria_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veterinariosVeterinaria', to='citas_veterinaria.veterianriamodel'),
        ),
        migrations.AlterField(
            model_name='veterinariomodel',
            name='veterinarioFoto',
            field=models.ImageField(db_column='veterinaria_foto', null=True, upload_to='veterinario/', verbose_name='Foto del veterinario'),
        ),
    ]
