# Generated by Django 3.1.7 on 2021-04-07 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas_veterinaria', '0008_auto_20210406_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotamodel',
            name='cita',
            field=models.ForeignKey(db_column='cita_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citaMascota', to='citas_veterinaria.citamodel'),
        ),
        migrations.AddField(
            model_name='mascotamodel',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mascotaUsuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='citamodel',
            name='sede',
            field=models.ForeignKey(db_column='sede_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sede', to='citas_veterinaria.sedemodel'),
        ),
        migrations.AlterField(
            model_name='citamodel',
            name='servicio',
            field=models.ForeignKey(db_column='servicio_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio', to='citas_veterinaria.serviciomodel'),
        ),
        migrations.AlterField(
            model_name='sedemodel',
            name='veterinaria',
            field=models.ForeignKey(db_column='veterinaria_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veterinariaSede', to='citas_veterinaria.veterianriamodel'),
        ),
        migrations.AlterField(
            model_name='veterinariomodel',
            name='veterinaria',
            field=models.ForeignKey(db_column='veterinaria_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veterinariosVeterinaria', to='citas_veterinaria.veterianriamodel'),
        ),
    ]
