# Generated by Django 3.1.7 on 2021-04-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_veterinaria', '0010_auto_20210409_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuarioFoto',
            field=models.ImageField(db_column='usuario_foto', default='default.png', null=True, upload_to='usuario/', verbose_name='Foto del usuario'),
        ),
    ]
