# Generated by Django 3.1.7 on 2021-04-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_veterinaria', '0010_auto_20210409_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomodel',
            name='servicioEstado',
            field=models.BooleanField(db_column='servicio_estado', default=True),
        ),
    ]
