# Generated by Django 3.1.7 on 2021-04-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_veterinaria', '0011_serviciomodel_servicioestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinariomodel',
            name='veterinarioEstado',
            field=models.BooleanField(db_column='especie_estado', default=True),
        ),
    ]
