# Generated by Django 3.1.7 on 2021-04-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_veterinaria', '0012_veterinariomodel_veterinarioestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotamodel',
            name='mascotaEstado',
            field=models.BooleanField(db_column='mascota_estado', default=True),
        ),
    ]
