# Generated by Django 3.1.7 on 2021-04-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas_veterinaria', '0013_mascotamodel_mascotaestado'),
        ('citas_veterinaria', '0009_auto_20210406_2357'),
        ('citas_veterinaria', '0012_auto_20210413_2054'),
    ]

    operations = [
    ]
